### ISSUE TITLE
Fulfill formal requirements

### ISSUE THREAD

**Issue by lroellin** [thde/sa#11]

**Comment by lroellin** [comment]
- [ ] Titelblatt: Titelblatt gemäss Vorlage. Es steht eine deutsche und eine englische Version zur Verfügung.

- [ ] Aufgabenstellung: Die vom Betreuer abgegebene und unterschriebene Aufgabenstellung (eingescannt).

**Comment by thde** [comment]
https://github.com/thde/sa/wiki/Meeting-Minutes
