### ISSUE TITLE
Find Web framework

### ISSUE THREAD

**Issue by lroellin** [thde/sa#12]
@thde found these that are written in Kotlin (if we use Kotlin):
* https://github.com/ktorio/ktor
* https://github.com/tipsy/javalin
* https://github.com/Tinder/Scarlet

**Comment by lroellin** [comment]
From a first glance:

* Ktor seems pretty nice and has some use cases in their tutorials that would suit us, e.g. http://ktor.io/quickstart/guides/chat.html
* Javalin has documentation in Java and Kotlin, meaning you could always check Java code if you don't understand a Kotlin language construct
* Scarlet looks like just a client?

**Comment by thde** [comment]
We try to use ktor: https://github.com/ktorio/ktor
