### ISSUE TITLE
Write project description

### ISSUE THREAD

**Issue by lroellin** [thde/sa#6]

**Comment by lroellin** [comment]
Once we know what we want to do, write up a proper project description (could even be a "Aufgabenstellung" as defined in https://wiki.hsr.ch/FarhadMehta/files/Aufgabenstellung-2015-HS-BA-Fluxron-Kayed-Winter_-_V0100_DE.pdf)

**Comment by lroellin** [comment]
Thomas will need to write it himself and sign it!

**Comment by thde** [comment]
Will be done later
